name: mkdocs
channels:
  - defaults
dependencies:
  - python=3.10  
  - pip
  - pip:
      - mkdocs
      - mkdocs-material
      - mkdocs-glightbox
      - mkdocs-statistics-plugin
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-callouts
      - mkdocs-minify-plugin
      - mkdocs-video
      - mkdocs-blogging-plugin